name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.8'
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET}}
    - run: dotnet build src/Singularis.Specification/Singularis.Specification.sln"        
    - name: Pack Singularis.Specification.Domain
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Domain/Singularis.Specification.Domain.csproj
    - name: Publish Singularis.Specification.Domain
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Domain/bin/Release/*.nupkg
    - name: Pack Singularis.Specification.Executor.Nhibernate
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Executor.Nhibernate/Singularis.Specification.Executor.Nhibernate.csproj
    - name: Singularis.Specification.Executor.Nhibernate
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Executor.Nhibernate/bin/RElease/*.nupkg
