name: build and publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.207'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET}}
    - name: Build
      run: dotnet build "src/Singularis.Specification/Singularis.Specification.sln"        
    - name: Pack Singularis.Specification.Definition
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Definition/Singularis.Specification.Definition.csproj
    - name: Publish Singularis.Specification.Definition
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Definition/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_SECRET}}
    - name: Pack Singularis.Specification.Executor.Common
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Executor.Common/Singularis.Specification.Executor.Common.csproj
    - name: Publish Singularis.Specification.Executor.Common
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Executor.Common/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_SECRET}}
    - name: Pack Singularis.Specification.Executor.EntityFramework
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Executor.EntityFramework/Singularis.Specification.Executor.EntityFramework.csproj
    - name: Publish Singularis.Specification.Executor.EntityFramework
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Executor.EntityFramework/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_SECRET}}      
    - name: Pack Singularis.Specification.Executor.Nhibernate
      run: dotnet pack --configuration Release src/Singularis.Specification/Singularis.Specification.Executor.Nhibernate/Singularis.Specification.Executor.Nhibernate.csproj
    - name: Publish Singularis.Specification.Executor.Nhibernate
      run: dotnet nuget push src/Singularis.Specification/Singularis.Specification.Executor.Nhibernate/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_SECRET}}
